version: "3"
services:

  postgres_db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped